name: immichframe
services:
  immichframe:
    container_name: immichframe
    image: ghcr.io/immichframe/immichframe:latest
    restart: on-failure
    # volumes:
    #   - PATH/TO/CONFIG:/app/Config
    #   - PATH/TO/CUSTOMCSS/custom.css:/app/wwwroot/static/custom.css
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      TZ: "Europe/Berlin"
